# Repo-name - The name of the repo
# Notes: This does not do anything, only used when notifying command sender.
# (But defined makes the command feedback better ;D)
repo-name: Repo

# repo-path: The directory path to the git repo. 
# Notes: Ensure this points to the root folder of a repo. A sub-folder may cause problems
repo-path: /

# ssh-passphrase - The passpharse if required
ssh-passphrase: password
